main : com.github.QCEconomy.Main
name : QCEconomy
version : 0.0.2
author : QC
description : QC Economy Plugin

commands:
  돈:
    description: 돈 관련 명령어
  
  돈관리:
    description: 돈 관련 어드민 명령어
  
  
  캐시관리:
    description: 캐시관련 어드민 명령어
  
  캐시:
    description: 캐시 관련 명령어